# Refer to https://wiki.hyprland.org/Configuring/Variables/
general {
    gaps_in = 7
    gaps_out = 12

    border_size = 1

    col.active_border = rgb(ffffff)
    col.inactive_border = rgba(ffffff69)

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 2

    active_opacity = .95
    inactive_opacity = 1
    dim_inactive = true
    dim_strength = 0.15

    shadow {
        enabled = false
        range = 6
        render_power = 4
        color = rgba(ffffff37)
    }

    blur {
    enabled = true
    size = 6
    passes = 1
    new_optimizations = true
    ignore_opacity = true
    popups = true
    input_methods = true
    contrast = 1
    brightness = 2
    }
}

windowrule = opaque yes, match:class steam
windowrule = opaque yes, float yes, match:class org.gnome.Showtime
windowrule = opaque yes, match:class Minecraft* 1.21.11
windowrule = animation slide, match:class wofi
windowrule = float yes, match:class hypremoji
windowrule {
	name = shimeji
	match:class = Shijima-Qt
	
    opaque = true
	float = true
	no_blur = true
	# no_focus = true
	no_shadow = true
	border_size = 0
}
layerrule = blur on, match:namespace waybar
