exec-once = waybar & hyprpaper & mako
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once=hyprctl setcursor phinger-cursors-light 24
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = shimejictl mascot summon Hornet
exec-once = ~/.config/hypr/shimeji-autohide.sh