# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
windowrule = opaque yes, match:class steam
windowrule = opaque yes, float yes, match:class org.gnome.Showtime
windowrule = opaque yes, match:class Minecraft* 1.21.11
windowrule = animation slide, match:class wofi
windowrule = float yes, match:class hypremoji
windowrule = float yes, match:class org.gnome.TextEditor
windowrule {
	name = shimeji
	match:class = Shijima-Qt
	
    opaque = true
	float = true
	no_blur = true
	no_shadow = true
	border_size = 0
}
layerrule {
  name = blur-waybar
  blur = on
  ignore_alpha = 0
  match:namespace = waybar
}